# Short python code to test the score of 2 sequences

def smith_waterman(s1, s2, match=1, mismatch=-1, gap=-1):
    m, n = len(s1), len(s2)
    H = [[0] * (n + 1) for _ in range(m + 1)]
    max_score = 0

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i-1] == s2[j-1]:
                score = match  
            else:
                score = mismatch

            H[i][j] = max(
                0,
                H[i-1][j-1] + score,
                H[i-1][j] + gap,
                H[i][j-1] + gap
            )
            max_score = max(max_score, H[i][j])
    
    return max_score

s1 = "CGTGAATCTCCGAGGTTGCTATAAGTGCATGTGTCGGAACAAGACAGACTCTTAGGTGCTGTGACCATCGCGAATGCCCCCCTGGTCAACGACGTCTATGTGTTTTACAGCTTCAGCTTCAAAAGTTTGCCATCTGTTGTTCCCTACCGTTAGGTGTGTAGATCTGGCTCCCTTCCGCATGCACATAGTTTGGGTCGGGTCCATCCTAGTCACGATATCCATGTGTCCCAAGGAGTTTAATTTCACTGGTGGCGCTGGAAGACTAAAATTGACTAGCTTGGCGTAAATCCTCGATACCACCGAACGCTCACGGTATAGCGAGTACACGATCATTCAGGAAGGAGTACCGTCTCCAACACCACAGTACGACCTGTGAAACAGAAGCTCCGGAACCGGAAATTATCCGAAGAGTCTGATGCTGTCCTGGTGGGGTGTAACATCGACGCGCCTTTGCTTAAGCCTGCTCGCGCTCTGTGACAGACAAGCGCTGCGTGCTGGAACATCACCATTTAGGTTCGGGGCCTCCGAGTCGTGCTCATGCGCGCAAGTTGAGCGATTTCAATACAAGCGATACTAAACGGAAACTGTATACATCTGTTCCCGTGGCTGGTCGTTTTGGACTGATTTACCTTTCGATTAACCGTGCTTGCTTTTAAACGGCAGGCCACCCTGCGTTGCACTAGACGGAAAAAGCGTAGCGCGTCGCCCCAGATTAGGCGGTAGTGCAGGAGTTGTTTCAGTTTGTTCGACACGGGCACCGTCGCGGGCGGGAGCATTCGGATTAAACGGGCCCTATCGCTTAGATGGTGGGTGGATAAGAATGTAGACCTCCTATAATTCGAGGGATGGAGAAACGAGGTACCGGGCCTGAGAGCCGACTAATGGGGAGCGTACCGTGATGTGTGGTTACCGTCGTTCGCACCATACATTAGGTTATACCATCTTGAGACGTATCGCGCGGGCACAAAATTAATGACGTGCATAAATTGCATGGGACATA"
s2 = "ATGGTAGTAGTGGTACAAAAAGTTGTTAAGTGTAATGACCCGGCCAAGGGCTCTGTTCTATACGCTCAGCTGCCCTTGGCGGTCAAACATATCTAGATCTGGCTGGAATACGATCCTGCGTAGACAACTTTTCATCCACTATATCGACGCATCGTGTGATCTCAAAACGGGCAGTTGTATGATTATAGTGATCTGTCTTAGACTAGCTATCCGTATTCAGAAGCTCGTTCTTCGGATATGAGAGGGGTGACAGCAACACTGAGTGGGTAGCCAGCGGTTATAAAAGCCGGCGGTGGCTTCGTGAAATTAAACACATCGCTGTAGAATTCCTTTGAACAAAATTGAGCAGTGTTAGGTCAAGTAGTCATCATTACTCGAGCCCGACGCCTTTCATCCCCCGGGGTTGTATAACGTCTCCGGACTACGCCGGGAGGACTCTCCGAAGTAATTTGTTATAACCAAATTCGCAAAAGTCGTACTCATTATTGCTGTTTTGCCATTTTCACCATACTCAACAACGACTCAAAACTCCCGGGACCCAGGAGGCTCACTGAATGAGCGTCATTCACATGAATGTGAAGCCCTCAGCATAACGGTGTGACAGCGTAAGGTTTAACACCTATGGACACCCGTGCGACTACCTTCAATGCGCGCAGGCATTCACACGGTCCAACCCAGGCTGGCTTCCGTGATCACTCGACTGCCGGTTTACACCGAATGTACTAGCACGAACCCGGATACCGTGACTAGTAATAGATTCCGTCCGTCGTTGTGTAACTCACGGTGCCTCATCCATGAGGGAAGGCAATCATTCCAGCTGGCCTCAGCCCTATATGAAGTAAGTAGCACGGAAGAGTACCAACGGAAACAGCTGCTCTGAAACGCGGCGATAAAAATTTCTTGTTAGATTGTACAATGCAGATCGCGAGCGTGAGAAATACTCACAGATGTCTAGCCGTGCCCTGGAACACAAGAGACACGTACTACTGTCATACAGAGC"
print(smith_waterman(s1, s2))  
